# pip install numpy

In [1]:
import numpy as np

array -> valorile sunt de acelasi tip 

lista -> valorile pot fi de tipuri diferite

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(type(arr), arr.dtype)

<class 'numpy.ndarray'> int64


In [7]:
arr = np.array([11, 22, 33, 44, 55, 66, 77])
arr

array([11, 22, 33, 44, 55, 66, 77])

# 1. Maparea

In [8]:
arr * 10

array([110, 220, 330, 440, 550, 660, 770])

In [10]:
lista = [11, 22, 33, 44, 55, 66, 77]
print(lista * 3)

[11, 22, 33, 44, 55, 66, 77, 11, 22, 33, 44, 55, 66, 77, 11, 22, 33, 44, 55, 66, 77]


In [11]:
lista = [11, 22, 33, 44, 55, 66, 77]
lista + lista

[11, 22, 33, 44, 55, 66, 77, 11, 22, 33, 44, 55, 66, 77]

In [12]:
arr = np.array([11, 22, 33, 44, 55, 66, 77])
arr - 5


array([ 6, 17, 28, 39, 50, 61, 72])

In [13]:
arr = np.array([11, 22, 33, 44, 55, 66, 77])
arr + arr 

array([ 22,  44,  66,  88, 110, 132, 154])

In [14]:
arr = np.array([11, 22, 33, 44, 55, 66, 77])
arr - arr 

array([0, 0, 0, 0, 0, 0, 0])

# 2 - Filtrare

In [15]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
arr % 2 == 0

array([False,  True, False,  True, False,  True, False])

In [16]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
arr [ arr % 2 == 0 ]

array([22, 44, 66])

In [17]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
conditie = arr % 2 == 0 
arr [ conditie ]

array([22, 44, 66])

In [18]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
conditie_1 = arr % 2 == 0 
arr[conditie_1] 


array([22, 44, 66])

In [19]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
conditie_2 = arr > 30
arr[conditie_2] 

array([33, 44, 55, 66, 77])

In [21]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
conditie_1 = arr % 2 == 0 
conditie_2 = arr > 30
arr[conditie_1 & conditie_2] 

array([44, 66])

# 3. Reduce

In [22]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
arr.sum()

np.int64(308)

In [23]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
arr.min()

np.int64(11)

In [24]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
arr.max()

np.int64(77)

In [25]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
arr.mean()

np.float64(44.0)

In [26]:
arr = np.array([11, 22, 33, 44, 55, 66, 77]) 
arr.size

7