In [1]:
import numpy as np

In [2]:
np.array([231, 412.0, 312, 31, True])

array([231., 412., 312.,  31.,   1.])

In [3]:
np.array([231, 412.0, 312, 31, True, "hello"])

array(['231', '412.0', '312', '31', 'True', 'hello'], dtype='<U32')

In [5]:
arr = np.array([231, 412.0, 312, 31, True, "hello"])
arr.shape

(6,)

In [9]:
arr = np.array([[231, 412.0, 312, 31], [True, 231, 312, 421]])
arr.shape

(2, 4)

In [10]:
np.random.random()

0.45887030954940133

In [11]:
np.random.random(10)

array([0.2776872 , 0.26759552, 0.27874631, 0.2843463 , 0.67443131,
       0.22150918, 0.0140106 , 0.60899325, 0.43462394, 0.07154422])

In [12]:
np.random.random((2, 3))

array([[0.85133835, 0.52499092, 0.28231759],
       [0.88500177, 0.74531584, 0.50734392]])

In [13]:
np.random.randint(1, 100, (4, 4))

array([[45, 51, 19, 16],
       [94, 78, 41, 49],
       [26, 96, 82, 23],
       [60, 34,  7, 83]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(10,dtype=np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
np.arange(100, 200)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [18]:
np.arange(100, 200, 5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [19]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [20]:
np.linspace(1, 100, 6)

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [22]:
arr = np.arange(100, 200, 5)
arr

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [23]:
arr.shape

(20,)

In [24]:
arr.reshape((4, 5))

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [25]:
arr.reshape((10, 2))

array([[100, 105],
       [110, 115],
       [120, 125],
       [130, 135],
       [140, 145],
       [150, 155],
       [160, 165],
       [170, 175],
       [180, 185],
       [190, 195]])