In [9]:
import numpy as np

In [10]:
startDate = 1600
stopDate = 2025

years = np.arange(startDate, stopDate + 1)
years

array([1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610,
       1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621,
       1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632,
       1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643,
       1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654,
       1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665,
       1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676,
       1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687,
       1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698,
       1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709,
       1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720,
       1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731,
       1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742,
       1743, 1744, 1745, 1746, 1747, 1748, 1749, 17

In [11]:
years[  (years % 400 == 0) ]

array([1600, 2000])

In [12]:
years[  (years % 4 == 0) & (years % 100 != 0) ]

array([1604, 1608, 1612, 1616, 1620, 1624, 1628, 1632, 1636, 1640, 1644,
       1648, 1652, 1656, 1660, 1664, 1668, 1672, 1676, 1680, 1684, 1688,
       1692, 1696, 1704, 1708, 1712, 1716, 1720, 1724, 1728, 1732, 1736,
       1740, 1744, 1748, 1752, 1756, 1760, 1764, 1768, 1772, 1776, 1780,
       1784, 1788, 1792, 1796, 1804, 1808, 1812, 1816, 1820, 1824, 1828,
       1832, 1836, 1840, 1844, 1848, 1852, 1856, 1860, 1864, 1868, 1872,
       1876, 1880, 1884, 1888, 1892, 1896, 1904, 1908, 1912, 1916, 1920,
       1924, 1928, 1932, 1936, 1940, 1944, 1948, 1952, 1956, 1960, 1964,
       1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2004, 2008, 2012,
       2016, 2020, 2024])

In [13]:
years[ ((years % 4 == 0) & (years % 100 != 0)) | (years % 400 == 0)  ]

array([1600, 1604, 1608, 1612, 1616, 1620, 1624, 1628, 1632, 1636, 1640,
       1644, 1648, 1652, 1656, 1660, 1664, 1668, 1672, 1676, 1680, 1684,
       1688, 1692, 1696, 1704, 1708, 1712, 1716, 1720, 1724, 1728, 1732,
       1736, 1740, 1744, 1748, 1752, 1756, 1760, 1764, 1768, 1772, 1776,
       1780, 1784, 1788, 1792, 1796, 1804, 1808, 1812, 1816, 1820, 1824,
       1828, 1832, 1836, 1840, 1844, 1848, 1852, 1856, 1860, 1864, 1868,
       1872, 1876, 1880, 1884, 1888, 1892, 1896, 1904, 1908, 1912, 1916,
       1920, 1924, 1928, 1932, 1936, 1940, 1944, 1948, 1952, 1956, 1960,
       1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004,
       2008, 2012, 2016, 2020, 2024])